select * from bank_loan_data;

SELECT
	COUNT(*) AS TOTAL_LOAN_APPLICATION
FROM
	BANK_LOAN_DATA;
	
SELECT DISTINCT
	ADDRESS_STATE,
	COUNT(ID) AS TOTAL_LOAN_APPLICATION
FROM
	BANK_LOAN_DATA
GROUP BY
	ADDRESS_STATE
ORDER BY
	TOTAL_LOAN_APPLICATION DESC
LIMIT
	5;
'null value handling'
update bank_loan_data set emp_title = 'other' where emp_title is null ;

SELECT
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	EMP_TITLE
FROM
	BANK_LOAN_DATA
GROUP BY
	EMP_TITLE
ORDER BY
	TOTAL_LOAN_APPLICATION DESC
LIMIT
	5;	

SELECT
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	GRADE
FROM
	BANK_LOAN_DATA
GROUP BY
	GRADE
ORDER BY
	TOTAL_LOAN_APPLICATION DESC;

SELECT
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	HOME_OWNERSHIP
FROM
	BANK_LOAN_DATA
GROUP BY
	HOME_OWNERSHIP
ORDER BY
	TOTAL_LOAN_APPLICATION DESC;

SELECT
	COUNT(*) AS TOTAL_LOAN_APPLICATION,
	TO_CHAR(ISSUE_DATE, 'month') AS MONTH
FROM
	BANK_LOAN_DATA
GROUP BY
	MONTH
ORDER BY
	TOTAL_LOAN_APPLICATION DESC;
	
SELECT
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	LOAN_STATUS
FROM
	BANK_LOAN_DATA
GROUP BY
	LOAN_STATUS
ORDER BY
	TOTAL_LOAN_APPLICATION DESC;

SELECT
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	PURPOSE
FROM
	BANK_LOAN_DATA
GROUP BY
	PURPOSE
ORDER BY
	TOTAL_LOAN_APPLICATION DESC;
SELECT
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	TERM
FROM
	BANK_LOAN_DATA
GROUP BY
	TERM;	
SELECT
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	VERIFICATION_STATUS
FROM
	BANK_LOAN_DATA
GROUP BY
	VERIFICATION_STATUS
ORDER BY
	TOTAL_LOAN_APPLICATION DESC;
SELECT
	SUM(LOAN_AMOUNT) AS FUNDED_AMOUNT
FROM
	BANK_LOAN_DATA;
	
SELECT
	ADDRESS_STATE,
	SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
FROM
	BANK_LOAN_DATA
GROUP BY
	ADDRESS_STATE
ORDER BY
	TOTAL_FUNDED_AMOUNT DESC
LIMIT
	5;


SELECT
	SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	TO_CHAR(ISSUE_DATE, 'month') AS MONTH
FROM
	BANK_LOAN_DATA
GROUP BY
	MONTH
ORDER BY
	TOTAL_FUNDED_AMOUNT DESC;

SELECT
	GRADE,
	SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT,
	COUNT(ID) AS TOTAL_LOAN_APPLICATION
FROM
	BANK_LOAN_DATA
GROUP BY
	GRADE
ORDER BY
	TOTAL_FUNDED_AMOUNT DESC;

SELECT
	MIN(ISSUE_DATE) AS FIRST_LONE_APPLICATION_DATE,
	MAX(ISSUE_DATE) AS LAST_LOAN_APPLICATION_DATE,
	MIN(LOAN_AMOUNT) AS MIN_FUNDED_AMOUNT,
	MAX(LOAN_AMOUNT) AS MAX_FUNDED_AMOUNT,
	MIN(TOTAL_PAYMENT) AS MIN_TOTAL_PAYMENT,
	MAX(TOTAL_PAYMENT) AS MAX_TOTAL_PAYMENT
FROM
	BANK_LOAN_DATA;
SELECT
	SUM(LOAN_AMOUNT) AS TOTAL_DUNDED_AMOUNT,
	TO_CHAR(ISSUE_DATE, 'month') AS MONTH
FROM
	BANK_LOAN_DATA
GROUP BY
	MONTH;

SELECT
	COUNT(*) AS TOTAL_LOAN_APPLICATION
FROM
	BANK_LOAN_DATA;	

SELECT
	SUM(LOAN_AMOUNT) AS TOTAL_FUNDED_AMOUNT
FROM
	BANK_LOAN_DATA;

SELECT
	SUM(TOTAL_PAYMENT) AS TOTAL_PAYMENT
FROM
	BANK_LOAN_DATA;
SELECT
	SUM(INTEREST_AMOUNT) AS TOTAL_INTEREST_AMOUNT
FROM
	BANK_LOAN_DATA;
SELECT
	COUNT(ID) AS TOTAL_LOAN_APPLICATION,
	GRADE
FROM
	BANK_LOAN_DATA
GROUP BY
	GRADE
ORDER BY
	GRADE ASC;

SELECT
	MAX(LOAN_AMOUNT) AS MAX_FUNDED_AMOUNT,
	ID AS CUSTOMER_ID
FROM
	BANK_LOAN_DATA
GROUP BY
	CUSTOMER_ID
ORDER BY
	MAX_FUNDED_AMOUNT DESC
LIMIT
	5;
	